spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: finalcase-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**,/api/v1/auth/**
        - id: real-estate-ads-service-secured
          uri: lb://AD-SERVICE
          predicates:
            - Path=/api/v1/ads/secure/**
          filters:
            - AuthFilter
        - id: real-estate-ads-service
          uri: lb://AD-SERVICE
          predicates:
            - Path=/api/v1/ads/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**
          filters:
            - AuthFilter
        - id: subscription-service
          uri: lb://SUBSCRIPTION-SERVICE
          predicates:
            - Path=/api/v1/subscriptions/**
server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway